

services:
  tablereservation:
    container_name: app
    build: ./
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: always

  databasereservation:
    image: postgres:latest
    container_name: databasetb
    environment:
      POSTGRES_USER: $DB__USERNAME
      POSTGRES_PASSWORD: $DB__PASSWORD
      POSTGRES_DB: $DB__NAME
      POSTGRES_PORT: 5432
    ports:
      - "6432:5432"
    volumes:
      - pgdatareservation:/var/lib/postgresql/data

volumes:
  pgdatareservation:
