"""create_at

Revision ID: b32e253180c2
Revises: 1847d6d111f9
Create Date: 2025-04-11 20:35:41.768983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32e253180c2'
down_revision: Union[str, None] = '1847d6d111f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('table', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'create_at')
    op.drop_column('reservation', 'create_at')
    # ### end Alembic commands ###
